version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medivault_db
    environment:
      POSTGRES_USER: medivault
      POSTGRES_PASSWORD: medivault_password
      POSTGRES_DB: medivault_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: medivault_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
